name: Build Test CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  ci-test:
    runs-on: tzrec-codestyle-runner
    container:
      image: mybigpai-public-registry.cn-beijing.cr.aliyuncs.com/easyrec/tzrec-devel:0.8
    steps:
      - name: FetchCommit ${{ github.event.pull_request.head.sha }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: run_${{ github.run_id }}
      - name: RunBuildTestCI
        id: run_build_test_ci
        run: |
          cd run_${{ github.run_id }}
          bash scripts/build_wheel.sh nightly
          find dist/ -name '*.whl' | xargs pip install
          mkdir -p tmp && cd tmp
          python -c "import tzrec"
